# ========================
# Configurações Quarkus
# ========================

# Server
quarkus.http.port=8080

# ========================
# Banco de Dados H2
# ========================
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:aluguelcarrosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=sa
quarkus.datasource.password=

# H2 Console
quarkus.h2.web.enabled=true

# ========================
# JPA / Hibernate
# ========================
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# ========================
# Logging
# ========================
quarkus.log.level=INFO
